name: power_setting_windows
description: A Flutter plugin for receiving Windows power setting notification.
version: 0.0.2
homepage: https://github.com/DeepHow/App-PowerSettingNotificationWindows

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  win32: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: PowerSettingWindowsPluginCApi
